### ISSUE TITLE
Missing changes in 2.4.6

### ISSUE THREAD

**Issue by jeff-matthews** [AdobeDocs/commerce-php#130]
Originally reported in https://github.com/magento/devdocs/issues/9549

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

In 2.4.6 releases notes, and in 2.4.6 breaking changes list, I did not see the fact that `catalog/seo/generate_category_product_rewrites` default value has been changed from 1 to 0.

Lucky me I found out before pushing 2.4.6 live. It could have cause seo issues.

https://github.com/magento/magento2/commit/78976ed4a52045872089e235b33a6ab13913c299

Another thing missing (breaking change) : Zend_Json cannot be used anymore.

**Comment by JacobBrownAustin** [comment]
Sorry.  You are right,  this should have been in release notes.

The default value for catalog/seo/generate_category_product_rewrites was changed from 1 to 0.  

When the option `Generate "category/product" URL Rewrites` is enabled,  categoriesUrlRewriteGenerate is run which takes a long time because it has to load all of the categories one at a time.

By changing the default for generate_category_product_rewrites to 0,  we can save a lot of time on import for stores that do not need this.

If this configuration hasn't been manually changed,  after upgrading,  the records in `catalog_url_rewrite_product_category` and `url_rewrite` tables are unchanged.  No new category rewrites after should be added.  

(This is different from the behavior of manually changing this configuration setting.  If you manually change it from `1` to `0` or default to `0`,  then it deletes all of the category rewrites from `url_rewrite` table,  and all records are deleted from `catalog_url_rewrite_product_category`.)
