### ISSUE TITLE
Missing many events, for example "sales_order_invoice_save_after"

### ISSUE THREAD

**Issue by srokatonie** [AdobeDocs/commerce-php#71]
Issue in /src/pages/development/components/events-and-observers/event-list.md

See https://www.simicart.com/blog/magento-2-events-list/ which has more comprehensive list. 

I could PR, but wondering if some parts could be automated (ie. "Origins" or "Classes raising the event" for each section) if I wanted

**Comment by dobooth** [comment]
@dshevtsov Is this something we automate?

**Comment by keharper** [comment]
@dshevtsov @dobooth As of Commerce 2.4.6, merchants will be able to generate a list of

**Comment by keharper** [comment]
@srokatonie The path in the Admin is **System** > **Events** > **Events**.

(Again, this is as of 2.4.6, and for Commerce customers only.)

The Development team has told me that there is no way generate a complete, accurate list of events. Some plugin events, for example, are produced created at runtime. Now that we have a way to list the known events and drill down into the payloads, I'm going to close the PR, because that's as far as we can go. I will add links to the Commerce Eventing docs, though.
